### ISSUE TITLE
Add dash

### ISSUE THREAD

**Issue by aldopain** [aldopain/cyberpunk#24]
Добавить рывок персонажа по направлению движения. 
Параметризация:
1. Скорость
2. Дальность
Если не ошибаюсь, "резкость" === "скорость" в контексте CC.Move().

**Comment by fshpsmgc** [comment]
Да, легко. Тупо берём позицию прицела и телепортируем туда игрока. ОХ ВЕЙТ

**Comment by aldopain** [comment]
АХАХПХАХАХХАХА

**Comment by aldopain** [comment]
Речь больше о следующем:
1. Надо ли
2. В какой именно форме (именно рывок, кувырок, перекат)
3. Копеечку о реализации между нами. Вообще стандартный CharacterController.Move сойдет, имхо.

**Comment by aldopain** [comment]
1. @danibord 
2. Ээээ, как именно? Просто я не совсем понимаю. Имхо, это просто Move с повышенной скоростью и меньшим смусом (для резкости)
3. Имхо, лучше дэшить игрока по направлению движения

НО ВСЕ ЭТИ ВОПРОСЫ БОЛЬШЕ К @danibord 

@DarkSamudra тебя тоже хочется выслушать!

**Comment by fshpsmgc** [comment]
2. Вообще да, можно. Так даже не придётся проверять, можно ли туда дэшить
3. Когда реализуем прицел, можно будет сделать и то, и то, а потом посмотреть. В крайнем случае, переключатель в меню

**Comment by aldopain** [comment]
@fshpsmgc
2. Просто я решительно против любых телепортов в игре кроме хардкодных (тип я знаю откуда и куда телепортирую на этапе разработки и уверен, что всё будет ок)
Мув имеет хорошую физику встроенную и параметризацию для решения таких проблем, так что го. 
3. Согласен, но предлагаю пока засандалить онли по направлению движения в качестве задачи с большим приоритетом. В эту таску впиливаю +- описание Дани, она отправляется в работу. Создай таску по дэшу по направлению прицела, повесь Label - NeedDiscussion, Minor, Script. 

@danibord глянь описание таски и аппрувни, что тебя всё устраивает.

**Comment by fshpsmgc** [comment]
@aldopain вообще, нормальная система прицела решит эту проблему с телепортом, потому что будет основана на рэйкастах. Плюс, в классе Crosshair будет информация об объекте. Короче, мы и так будем знать, куда телепортируем. Но вообще да, рывок лучше сделать именно через CharacterController
