### ISSUE TITLE
Add spawn script and spawn trigger to enemy

### ISSUE THREAD

**Issue by aldopain** [aldopain/cyberpunk#41]
Добавить скрипт спавна врагов. 
1. Создать интерфейс для спавна, на основе которого будут реализованы различные типы спавна ("рация", зерг раш, тревога)
2*. Скрипт спавна смотрит на позицию маячка и на позицию игрока. Если игрок предположительно не видит позицию маячка (для этого вычислить, как далеко может посмотреть игрок, но это фича, которую можно добавить потом), то работаем дальше, иначе ну нахер.
3. Спавним N врагов установленных типов (реализовать массивом мапов ключ - значение, где ключ - тип врага (префаб, передаваемый в цикл Instantiate), а значение - количество итераций цикла)
4. У заспавненных врагов есть различные настройки состояния (спокойный, патруль, агро)

**Comment by fshpsmgc** [comment]
Спавнеры -- да, сделаем обязательно, но твоя реализация так себе. Их лучше не привязывать к врагу, а сделать отдельный, настраиваемый объект, который будет предоставлять интерфейсы для других объектов (триггеры и враги, например).
Я бы реализовал спавнеры следующим образом :
Есть одна публичная статичная функция Spawn, которая принимает аргументом индекс одного из объектов, который нужно создать. Создаёт объект в трансформе, учитывая настройки.
Собственно, массив объектов, который может заспавнить этот спавнер.
Точка появления объекта -- трансформ спавнера.
Настройки:
Лимит спавнов (0 для бесконечности);
Состояние заспавненного объекта (если спавним врага) -- спокойный, патруль, агро;
Прочие параметры, которые будут кастомизировать появившийся объект

**Comment by fshpsmgc** [comment]
С пунктом про вычисление видит/не видит ли игрок спавнер согласен отчасти. Нужно добавить возможность зафорсить спавн из редактора

**Comment by fshpsmgc** [comment]
(отвратительно, что кнопка изменения коммента не работает с телефона)
Спавнеры должны быть больше инструментом левел-дизайнера. Левел-дизайнер должен иметь возможность расставлять их при создании уровня, а твоя система очень сильно это ограничивает, потому что она привязана к врагам. Плюс, насколько я понял, если врага убивают, то и спавнер пропадает. Плюс, под эту систему придётся костылить свой триггер -- она, скорее всего не будет работать с нашими универсальными триггерами.

**Comment by aldopain** [comment]
@fshpsmgc объясняю, почему, имхо, нужна привязка к конкретному врагу либо к какой-нибудь панели (в моем воспаленном сознании представлялось что-то вроде рации, по которой враг зовет подкрепление)
Фишка в том, что на лвле будет в РАЗЫ меньше врагов (специально для стелса), чем нужно для шутера. Как это работает. Допустим у нас N врагов, ты проходишь в шутере. Тогда каждый враг при триггере спаунит k врагов, чтобы жизнь мёдом не казалась, и были сраные толпы уродов как в Alien Shooter, например. Итого это k*N тел. Теперь допустим, ты проходишь в стелсе. Тебе проще, потому что нужно обойти N тел, а не k*N (а k*N это когда лвл просто завален уродами). Насчет привязки к врагу согласен, идея такая себе, лучше всё же что-то вроде панели тревоги, решает достаточно много проблем. 
![image](https://user-images.githubusercontent.com/18515380/45469558-a50adb00-b732-11e8-9067-5c92d84ed77f.png)

**Comment by fshpsmgc** [comment]
Вообще, я предлагаю создать базовый класс, который будет предоставлять интерфейс. А уж как мы его будем использовать -- другое дело. Враг, который может вызывать подкрепление -- окей, мы берём класс ReinforcementCaller и циклом вызываем каждого врага со спавн поинтов. Терминал, вызывающий подкрепление -- та же идея, но по нажатию кнопки. Нужно, чтобы при входе в комнату спавнились враги -- вешаем на OnEnter нашего триггера спавн. Плюс, для длинных экшн-сцен мы просто ставим какой-нибудь флаг Infinite, чтобы новый враг спавнился при убийстве старого

**Comment by aldopain** [comment]
Ну ессно это должно быть абстрактно, я не строго говорю, мол, ВОТ 2 УРОВНЯ АБСТРАКЦИИ, ВСЁ, ТОЧКА
Тип, _как_ это будет вызываться, это не особо важно именно в таске, имхо, такую логику лучше оставить для этапа разработки уже.

**Comment by aldopain** [comment]
Но тип я только за.

**Comment by danibord** [comment]
Я не совсем понял пришли ли вы к какому-то единому мнению, но я согласен с вами в комментариях, которые лайкнул.
