### ISSUE TITLE
Add rocket launcher

### ISSUE THREAD

**Issue by aldopain** [aldopain/cyberpunk#42]
Добавить ракетницу, работающую с помощью OverlapSphere и реев. Протестировать просадку фпс при последовательном пуске большого количества ракет.

**Comment by danibord** [comment]
Ты уверен, что это так необходимо?)))

**Comment by aldopain** [comment]
@danibord так на ней и висит тег Minor)
Нам нужно несколько типов оружия, чтобы потом их добавление было простым.
