### ISSUE TITLE
Add door script

### ISSUE THREAD

**Issue by aldopain** [aldopain/cyberpunk#95]
Добавить реализацию дверей. 
2 класса - родитель и наследник. 
Родитель реализует простые функции Open() и Close(), которые открывают/закрывают дверь. 
Вызов этих функций автоматически реализовать с помощью триггеров Сени. 
Наследник реализует более сложный вариант двери, открывающейся по ключу. 
1. Дверь имеет 2 коллайдера - меш/бокс коллайдер для самой двери и бокс коллайдер с триггером для открытия/закрытия. 
2. Когда в коолайдер-триггер попадает объект, скрипт чекает, кто это. 
Если это враг - дверь открывается автоматом. 
Если это игрок - дверь чекает инвентарь на наличие ключа (пока оставить просто заглушку с true/false). Далее, если ключ есть, то дверь открывается, если нет, то нет.

**Comment by fshpsmgc** [comment]
По возможности максимально параметризовать код (скорость открывания, например)
Добавить UnityEvent’ы OnOpen и OnClose
